//! Command implementations

pub mod benchmark;
pub mod chat;
pub mod clip;
pub mod completions;
pub mod config_cmd;
pub mod doctor;
pub mod drop_box;
pub mod history;
pub mod identity;
pub mod man_pages;
pub mod proxy;
pub mod receive;
pub mod send;
pub mod speed_test;
pub mod ssh_setup;
pub mod sync;
pub mod tui_cmd;
pub mod version;
pub mod watch;
