// Type declarations for WASM-generated bindings
// These are generated by wasm-bindgen but we provide stubs for TypeScript checking

export default function init(): Promise<void>;

// Crypto
export class WasmKeyPair {
    static generate(): WasmKeyPair;
    publicKeyBytes(): Uint8Array;
    decapsulate(ciphertext: Uint8Array): Uint8Array;
}

export class WasmEncapsulated {
    ciphertext(): Uint8Array;
    sharedSecret(): Uint8Array;
}

export function kemEncapsulate(publicKey: Uint8Array): WasmEncapsulated;
export function encryptChunk(key: Uint8Array, nonceCounter: bigint, aad: Uint8Array, plaintext: Uint8Array): Uint8Array;
export function decryptChunk(key: Uint8Array, nonceCounter: bigint, aad: Uint8Array, ciphertext: Uint8Array): Uint8Array;
export function blake3Hash(data: Uint8Array): Uint8Array;
export function blake3DeriveRoomId(codePhrase: string): Uint8Array;
export function hkdfDerive(ikm: Uint8Array, salt: Uint8Array, info: Uint8Array, outputLen: number): Uint8Array;
export function encryptChatMessage(key: Uint8Array, counter: bigint, plaintext: string): Uint8Array;
export function decryptChatMessage(key: Uint8Array, counter: bigint, ciphertext: Uint8Array): string;

// Codec
export function encodeMessage(msg: any): Uint8Array;
export function decodeMessage(bytes: Uint8Array): any;
export function encodeRoomJoin(roomId: Uint8Array, passwordHash?: Uint8Array): Uint8Array;
export function encodeFileOffer(transferId: Uint8Array, manifest: Uint8Array): Uint8Array;
export function encodeFileAccept(transferId: Uint8Array): Uint8Array;
export function encodeChunk(transferId: Uint8Array, index: bigint, total: bigint | undefined, data: Uint8Array): Uint8Array;
export function encodeAck(transferId: Uint8Array, index: bigint): Uint8Array;
export function encodeChatText(messageId: Uint8Array, sequence: number, ciphertext: Uint8Array, nonce: Uint8Array): Uint8Array;
export function encodeTypingIndicator(typing: boolean): Uint8Array;
export function encodeHandshakeInit(protocolVersion: number, kemCapabilities: Uint8Array, cpacePublic: Uint8Array, nonce: Uint8Array): Uint8Array;
export function encodeHandshakeResponse(selectedKem: number, cpacePublic: Uint8Array, kemPublicKey: Uint8Array, nonce: Uint8Array): Uint8Array;
export function encodeHandshakeKem(kemCiphertext: Uint8Array, confirmation: Uint8Array): Uint8Array;
export function encodeHandshakeComplete(confirmation: Uint8Array): Uint8Array;
export function encodeTransferComplete(transferId: Uint8Array, hash: Uint8Array, merkleRoot?: Uint8Array): Uint8Array;
export function encodePing(): Uint8Array;
export function encodePong(): Uint8Array;
export function sanitizeDisplayText(input: string): string;

// Transport
export class WsTransport {
    constructor();
    prepareRoomJoin(roomId: Uint8Array, passwordHash?: Uint8Array): Uint8Array;
    prepareRoomJoinMulti(roomId: Uint8Array, passwordHash: Uint8Array | undefined, capacity: number): Uint8Array;
    parseRoomResponse(data: Uint8Array): any;
}

// Transfer
export class TransferSession {
    constructor(sessionKey: Uint8Array, transferId: Uint8Array);
    prepareFileOffer(manifestBytes: Uint8Array): Uint8Array;
    prepareChunk(index: number, total: number | undefined, plaintext: Uint8Array): Uint8Array;
    decryptChunk(index: number, encryptedData: Uint8Array): Uint8Array;
    prepareAck(index: number): Uint8Array;
    prepareTransferComplete(hash: Uint8Array, merkleRoot?: Uint8Array): Uint8Array;
    prepareFileAccept(): Uint8Array;
    prepareFileReject(reason: string): Uint8Array;
    currentChunkIndex(): number;
    transferId(): Uint8Array;
}

// File I/O
export function computeFileManifest(filesJson: string): Uint8Array;
export function parseFileManifest(manifestBytes: Uint8Array): any;
