/**
 * Feature Catalog - Comprehensive listing of all Tallow features
 * Over 200 features across security, transfer, network, privacy, UI, and more
 */

export interface Feature {
  id: string;
  title: string;
  description: string;
  category:
    | 'security'
    | 'transfer'
    | 'network'
    | 'privacy'
    | 'ui'
    | 'chat'
    | 'friends'
    | 'settings'
    | 'crypto'
    | 'performance';
  status: 'implemented' | 'planned' | 'in-progress';
  icon: string;
  details?: string;
  relatedFiles?: string[];
}

export const FEATURES: Feature[] = [
  // Security Features (40+)
  {
    id: 'sec-001',
    title: 'AES-256-GCM Encryption',
    description: 'Military-grade end-to-end encryption for all file transfers',
    category: 'security',
    status: 'implemented',
    icon: '🔒',
    details: 'All files are encrypted with AES-256-GCM before transmission. Keys are generated per-session and never stored.',
    relatedFiles: ['lib/crypto/file-encryption.ts'],
  },
  {
    id: 'sec-002',
    title: 'Post-Quantum Cryptography',
    description: 'ML-KEM (Kyber) key encapsulation for quantum-resistant security',
    category: 'security',
    status: 'implemented',
    icon: '🛡️',
    details: 'NIST-standardized ML-KEM-768 provides protection against quantum computer attacks.',
    relatedFiles: ['lib/crypto/pqc-crypto.ts'],
  },
  {
    id: 'sec-003',
    title: 'Triple Ratchet Protocol',
    description: 'Advanced forward secrecy with triple ratchet key rotation',
    category: 'security',
    status: 'implemented',
    icon: '🔄',
    details: 'Combines symmetric, asymmetric, and post-quantum ratchets for maximum security.',
    relatedFiles: ['lib/crypto/triple-ratchet.ts'],
  },
  {
    id: 'sec-004',
    title: 'Zero-Knowledge Architecture',
    description: 'Server never sees your files or encryption keys',
    category: 'security',
    status: 'implemented',
    icon: '👁️',
  },
  {
    id: 'sec-005',
    title: 'Digital Signatures',
    description: 'Verify file integrity and sender authenticity',
    category: 'security',
    status: 'implemented',
    icon: '✍️',
    relatedFiles: ['lib/crypto/digital-signatures.ts'],
  },
  {
    id: 'sec-006',
    title: 'Peer Authentication',
    description: 'Cryptographic verification of peer identities',
    category: 'security',
    status: 'implemented',
    icon: '🎫',
    relatedFiles: ['lib/crypto/peer-authentication.ts'],
  },
  {
    id: 'sec-007',
    title: 'Password Protection',
    description: 'Optional password encryption for shared files',
    category: 'security',
    status: 'implemented',
    icon: '🔑',
    relatedFiles: ['lib/crypto/password-protection.ts'],
  },
  {
    id: 'sec-008',
    title: 'ChaCha20-Poly1305',
    description: 'Fast, secure stream cipher for high-performance encryption',
    category: 'security',
    status: 'implemented',
    icon: '⚡',
    relatedFiles: ['lib/crypto/chacha20-poly1305.ts'],
  },
  {
    id: 'sec-009',
    title: 'Argon2 Key Derivation',
    description: 'Memory-hard password hashing resistant to GPU attacks',
    category: 'security',
    status: 'implemented',
    icon: '🔐',
    relatedFiles: ['lib/crypto/argon2-browser.ts'],
  },
  {
    id: 'sec-010',
    title: 'Secure Memory Wiping',
    description: 'Cryptographic erasure of sensitive data from memory',
    category: 'security',
    status: 'implemented',
    icon: '🧹',
    relatedFiles: ['lib/security/memory-wiper.ts'],
  },
  {
    id: 'sec-011',
    title: 'Timing-Safe Comparisons',
    description: 'Constant-time operations prevent timing attacks',
    category: 'security',
    status: 'implemented',
    icon: '⏱️',
    relatedFiles: ['lib/security/timing-safe.ts'],
  },
  {
    id: 'sec-012',
    title: 'CSRF Protection',
    description: 'Cross-Site Request Forgery tokens for API security',
    category: 'security',
    status: 'implemented',
    icon: '🛡️',
    relatedFiles: ['lib/security/csrf.ts'],
  },
  {
    id: 'sec-013',
    title: 'Rate Limiting',
    description: 'Prevent abuse with intelligent rate limiting',
    category: 'security',
    status: 'implemented',
    icon: '🚦',
    relatedFiles: ['middleware/rate-limit.ts'],
  },
  {
    id: 'sec-014',
    title: 'Input Validation',
    description: 'Comprehensive validation prevents injection attacks',
    category: 'security',
    status: 'implemented',
    icon: '✅',
    relatedFiles: ['lib/validation/schemas.ts'],
  },
  {
    id: 'sec-015',
    title: 'Credential Encryption',
    description: 'Encrypted storage of sensitive credentials',
    category: 'security',
    status: 'implemented',
    icon: '🔐',
    relatedFiles: ['lib/security/credential-encryption.ts'],
  },
  {
    id: 'sec-016',
    title: 'Key Rotation',
    description: 'Automatic rotation of encryption keys',
    category: 'security',
    status: 'implemented',
    icon: '🔄',
    relatedFiles: ['lib/security/key-rotation.ts'],
  },
  {
    id: 'sec-017',
    title: 'Nonce Management',
    description: 'Secure generation and tracking of cryptographic nonces',
    category: 'security',
    status: 'implemented',
    icon: '🎲',
    relatedFiles: ['lib/crypto/nonce-manager.ts'],
  },
  {
    id: 'sec-018',
    title: 'WebRTC Security',
    description: 'DTLS-SRTP encrypted peer connections',
    category: 'security',
    status: 'implemented',
    icon: '🔒',
  },
  {
    id: 'sec-019',
    title: 'Secure Logger',
    description: 'Sanitized logging prevents credential leaks',
    category: 'security',
    status: 'implemented',
    icon: '📝',
    relatedFiles: ['lib/utils/secure-logger.ts'],
  },
  {
    id: 'sec-020',
    title: 'Memory Protection',
    description: 'Protected memory regions for sensitive data',
    category: 'security',
    status: 'implemented',
    icon: '🧠',
    relatedFiles: ['lib/security/memory-protection.ts'],
  },
  {
    id: 'sec-021',
    title: 'Room-Based Encryption',
    description: 'Separate encryption contexts for transfer rooms',
    category: 'security',
    status: 'implemented',
    icon: '🚪',
    relatedFiles: ['lib/crypto/room-crypto.ts'],
  },
  {
    id: 'sec-022',
    title: 'PQ Signatures',
    description: 'Post-quantum digital signatures for long-term security',
    category: 'security',
    status: 'implemented',
    icon: '📜',
    relatedFiles: ['lib/crypto/pq-signatures.ts'],
  },
  {
    id: 'sec-023',
    title: 'Sparse PQ Ratchet',
    description: 'Efficient post-quantum ratcheting for large transfers',
    category: 'security',
    status: 'implemented',
    icon: '⚡',
    relatedFiles: ['lib/crypto/sparse-pq-ratchet.ts'],
  },
  {
    id: 'sec-024',
    title: 'Serialization Security',
    description: 'Safe serialization prevents prototype pollution',
    category: 'security',
    status: 'implemented',
    icon: '📦',
    relatedFiles: ['lib/crypto/serialization.ts'],
  },
  {
    id: 'sec-025',
    title: 'PQC Signaling',
    description: 'Post-quantum secure WebRTC signaling',
    category: 'security',
    status: 'implemented',
    icon: '📡',
    relatedFiles: ['lib/crypto/pqc-signaling.ts'],
  },
  {
    id: 'sec-026',
    title: 'API Authentication',
    description: 'Secure API endpoints with token-based auth',
    category: 'security',
    status: 'implemented',
    icon: '🔑',
  },
  {
    id: 'sec-027',
    title: 'Transport Security',
    description: 'HTTPS-only with HSTS headers',
    category: 'security',
    status: 'implemented',
    icon: '🔒',
  },
  {
    id: 'sec-028',
    title: 'Content Security Policy',
    description: 'CSP headers prevent XSS attacks',
    category: 'security',
    status: 'implemented',
    icon: '🛡️',
  },
  {
    id: 'sec-029',
    title: 'Subresource Integrity',
    description: 'SRI tags for external resources',
    category: 'security',
    status: 'implemented',
    icon: '✅',
  },
  {
    id: 'sec-030',
    title: 'IP Leak Prevention',
    description: 'Prevent WebRTC IP leaks',
    category: 'security',
    status: 'implemented',
    icon: '🌐',
  },
  {
    id: 'sec-031',
    title: 'Secure Random Generation',
    description: 'Cryptographically secure random number generation',
    category: 'security',
    status: 'implemented',
    icon: '🎲',
  },
  {
    id: 'sec-032',
    title: 'Key Management',
    description: 'Secure lifecycle management of encryption keys',
    category: 'security',
    status: 'implemented',
    icon: '🔑',
    relatedFiles: ['lib/crypto/key-management.ts'],
  },
  {
    id: 'sec-033',
    title: 'Session Timeout',
    description: 'Automatic session expiration for security',
    category: 'security',
    status: 'implemented',
    icon: '⏰',
  },
  {
    id: 'sec-034',
    title: 'Secure Deletion',
    description: 'Cryptographic file deletion after transfer',
    category: 'security',
    status: 'implemented',
    icon: '🗑️',
    relatedFiles: ['lib/privacy/secure-deletion.ts'],
  },
  {
    id: 'sec-035',
    title: 'Audit Logging',
    description: 'Secure audit trails for security events',
    category: 'security',
    status: 'implemented',
    icon: '📋',
  },
  {
    id: 'sec-036',
    title: 'Screen Sharing PQC',
    description: 'Post-quantum encryption for screen sharing',
    category: 'security',
    status: 'implemented',
    icon: '🖥️',
  },
  {
    id: 'sec-037',
    title: 'Chat Security',
    description: 'End-to-end encrypted peer-to-peer chat',
    category: 'security',
    status: 'implemented',
    icon: '💬',
    relatedFiles: ['lib/chat/chat-security.ts'],
  },
  {
    id: 'sec-038',
    title: 'File Hash Verification',
    description: 'SHA-256 hashing verifies file integrity',
    category: 'security',
    status: 'implemented',
    icon: '#️⃣',
  },
  {
    id: 'sec-039',
    title: 'Browser Security Headers',
    description: 'X-Frame-Options, X-Content-Type-Options, etc.',
    category: 'security',
    status: 'implemented',
    icon: '🔒',
  },
  {
    id: 'sec-040',
    title: 'Secure Websocket',
    description: 'WSS protocol for encrypted signaling',
    category: 'security',
    status: 'implemented',
    icon: '🔌',
  },

  // Transfer Features (50+)
  {
    id: 'trans-001',
    title: 'Direct P2P Transfer',
    description: 'Files transfer directly between devices via WebRTC',
    category: 'transfer',
    status: 'implemented',
    icon: '🔄',
  },
  {
    id: 'trans-002',
    title: 'Resumable Transfers',
    description: 'Automatically resume interrupted transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '▶️',
    relatedFiles: ['lib/transfer/resumable-transfer.ts'],
  },
  {
    id: 'trans-003',
    title: 'File Chunking',
    description: 'Smart chunking for efficient large file transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '📦',
    relatedFiles: ['lib/transfer/file-chunking.ts'],
  },
  {
    id: 'trans-004',
    title: 'Folder Transfers',
    description: 'Transfer entire directory structures',
    category: 'transfer',
    status: 'implemented',
    icon: '📁',
    relatedFiles: ['lib/transfer/folder-transfer.ts'],
  },
  {
    id: 'trans-005',
    title: 'Group Transfers',
    description: 'Send files to up to 10 recipients simultaneously',
    category: 'transfer',
    status: 'implemented',
    icon: '👥',
    relatedFiles: ['lib/transfer/group-transfer-manager.ts'],
  },
  {
    id: 'trans-006',
    title: 'Transfer Progress',
    description: 'Real-time progress tracking with speed metrics',
    category: 'transfer',
    status: 'implemented',
    icon: '📊',
  },
  {
    id: 'trans-007',
    title: 'Transfer Manager',
    description: 'Orchestrates complex multi-file transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '🎯',
    relatedFiles: ['lib/transfer/transfer-manager.ts'],
  },
  {
    id: 'trans-008',
    title: 'Adaptive Bitrate',
    description: 'Dynamically adjust transfer speed based on network',
    category: 'transfer',
    status: 'implemented',
    icon: '⚡',
    relatedFiles: ['lib/transfer/adaptive-bitrate.ts'],
  },
  {
    id: 'trans-009',
    title: 'Parallel Channels',
    description: 'Multiple WebRTC channels for faster transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '🚀',
    relatedFiles: ['lib/webrtc/parallel-channels.ts'],
  },
  {
    id: 'trans-010',
    title: 'Transfer Rooms',
    description: 'Create persistent rooms for group collaboration',
    category: 'transfer',
    status: 'implemented',
    icon: '🏠',
    relatedFiles: ['lib/rooms/transfer-room-manager.ts'],
  },
  {
    id: 'trans-011',
    title: 'Drag and Drop',
    description: 'Intuitive drag-and-drop file selection',
    category: 'transfer',
    status: 'implemented',
    icon: '🖱️',
  },
  {
    id: 'trans-012',
    title: 'Transfer History',
    description: 'View and manage past transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '📜',
  },
  {
    id: 'trans-013',
    title: 'Transfer Cancel',
    description: 'Gracefully cancel in-progress transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '⛔',
  },
  {
    id: 'trans-014',
    title: 'Transfer Pause',
    description: 'Pause and resume transfers on demand',
    category: 'transfer',
    status: 'implemented',
    icon: '⏸️',
  },
  {
    id: 'trans-015',
    title: 'Transfer Queue',
    description: 'Queue multiple transfers for sequential processing',
    category: 'transfer',
    status: 'implemented',
    icon: '📋',
  },
  {
    id: 'trans-016',
    title: 'Transfer Notifications',
    description: 'Desktop notifications for transfer events',
    category: 'transfer',
    status: 'implemented',
    icon: '🔔',
  },
  {
    id: 'trans-017',
    title: 'Transfer Compression',
    description: 'Optional compression for faster transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '🗜️',
  },
  {
    id: 'trans-018',
    title: 'Transfer Limits',
    description: 'Configurable file size and count limits',
    category: 'transfer',
    status: 'implemented',
    icon: '⚖️',
  },
  {
    id: 'trans-019',
    title: 'Bandwidth Control',
    description: 'Throttle transfer speed to save bandwidth',
    category: 'transfer',
    status: 'implemented',
    icon: '🎚️',
  },
  {
    id: 'trans-020',
    title: 'Transfer Statistics',
    description: 'Detailed statistics for completed transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '📈',
  },
  {
    id: 'trans-021',
    title: 'Multi-File Selection',
    description: 'Select and send multiple files at once',
    category: 'transfer',
    status: 'implemented',
    icon: '📑',
  },
  {
    id: 'trans-022',
    title: 'File Preview',
    description: 'Preview files before sending',
    category: 'transfer',
    status: 'implemented',
    icon: '👁️',
  },
  {
    id: 'trans-023',
    title: 'Transfer Scheduling',
    description: 'Schedule transfers for later',
    category: 'transfer',
    status: 'planned',
    icon: '📅',
  },
  {
    id: 'trans-024',
    title: 'Transfer Expiration',
    description: 'Auto-expire shared links after time limit',
    category: 'transfer',
    status: 'implemented',
    icon: '⏰',
  },
  {
    id: 'trans-025',
    title: 'Transfer Modes',
    description: 'Choose between speed, balanced, or privacy modes',
    category: 'transfer',
    status: 'implemented',
    icon: '🎛️',
    relatedFiles: ['lib/transfer/transfer-mode-integration.ts'],
  },
  {
    id: 'trans-026',
    title: 'PQC Transfer',
    description: 'Post-quantum encrypted transfer protocol',
    category: 'transfer',
    status: 'implemented',
    icon: '🔒',
    relatedFiles: ['lib/transfer/pqc-transfer-manager.ts'],
  },
  {
    id: 'trans-027',
    title: 'Chunked Encryption',
    description: 'Encrypt files in chunks for streaming',
    category: 'transfer',
    status: 'implemented',
    icon: '🔐',
    relatedFiles: ['lib/transfer/encryption-chacha.ts'],
  },
  {
    id: 'trans-028',
    title: 'Transfer Benchmarks',
    description: 'Performance benchmarking for transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '🏁',
    relatedFiles: ['lib/transfer/benchmarks.ts'],
  },
  {
    id: 'trans-029',
    title: 'Automatic Retry',
    description: 'Retry failed chunks automatically',
    category: 'transfer',
    status: 'implemented',
    icon: '🔁',
  },
  {
    id: 'trans-030',
    title: 'Transfer Verification',
    description: 'Verify transfer integrity with checksums',
    category: 'transfer',
    status: 'implemented',
    icon: '✅',
  },
  {
    id: 'trans-031',
    title: 'Streaming Transfer',
    description: 'Stream large files without loading entirely',
    category: 'transfer',
    status: 'implemented',
    icon: '🌊',
  },
  {
    id: 'trans-032',
    title: 'Zero-Copy Transfer',
    description: 'Efficient memory handling for large files',
    category: 'transfer',
    status: 'implemented',
    icon: '⚡',
  },
  {
    id: 'trans-033',
    title: 'Link Sharing',
    description: 'Generate shareable links for transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '🔗',
  },
  {
    id: 'trans-034',
    title: 'QR Code Transfer',
    description: 'Generate QR codes for easy mobile transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '📱',
  },
  {
    id: 'trans-035',
    title: 'Clipboard Integration',
    description: 'Copy and paste files from clipboard',
    category: 'transfer',
    status: 'implemented',
    icon: '📋',
  },
  {
    id: 'trans-036',
    title: 'Download Manager',
    description: 'Manage and track incoming downloads',
    category: 'transfer',
    status: 'implemented',
    icon: '⬇️',
  },
  {
    id: 'trans-037',
    title: 'Upload Manager',
    description: 'Track and control file uploads',
    category: 'transfer',
    status: 'implemented',
    icon: '⬆️',
  },
  {
    id: 'trans-038',
    title: 'Transfer Recovery',
    description: 'Recover from network failures automatically',
    category: 'transfer',
    status: 'implemented',
    icon: '🔧',
  },
  {
    id: 'trans-039',
    title: 'Batch Transfers',
    description: 'Process multiple transfers in batches',
    category: 'transfer',
    status: 'implemented',
    icon: '📦',
  },
  {
    id: 'trans-040',
    title: 'Transfer Templates',
    description: 'Save and reuse transfer configurations',
    category: 'transfer',
    status: 'planned',
    icon: '📝',
  },
  {
    id: 'trans-041',
    title: 'Recipient Confirmation',
    description: 'Require recipient to accept before transfer',
    category: 'transfer',
    status: 'implemented',
    icon: '✋',
  },
  {
    id: 'trans-042',
    title: 'Transfer Analytics',
    description: 'Analyze transfer patterns and performance',
    category: 'transfer',
    status: 'implemented',
    icon: '📊',
  },
  {
    id: 'trans-043',
    title: 'One-Time Transfers',
    description: 'Self-destructing transfers after download',
    category: 'transfer',
    status: 'implemented',
    icon: '💥',
  },
  {
    id: 'trans-044',
    title: 'Transfer Tags',
    description: 'Organize transfers with custom tags',
    category: 'transfer',
    status: 'planned',
    icon: '🏷️',
  },
  {
    id: 'trans-045',
    title: 'Transfer Search',
    description: 'Search through transfer history',
    category: 'transfer',
    status: 'implemented',
    icon: '🔍',
  },
  {
    id: 'trans-046',
    title: 'Mobile Optimized',
    description: 'Optimized transfer experience for mobile',
    category: 'transfer',
    status: 'implemented',
    icon: '📱',
  },
  {
    id: 'trans-047',
    title: 'Offline Queuing',
    description: 'Queue transfers when offline, send when online',
    category: 'transfer',
    status: 'planned',
    icon: '📴',
  },
  {
    id: 'trans-048',
    title: 'Transfer Favorites',
    description: 'Mark and quickly access favorite recipients',
    category: 'transfer',
    status: 'planned',
    icon: '⭐',
  },
  {
    id: 'trans-049',
    title: 'Automatic Cleanup',
    description: 'Auto-delete old transfers to save space',
    category: 'transfer',
    status: 'implemented',
    icon: '🧹',
  },
  {
    id: 'trans-050',
    title: 'Transfer Comments',
    description: 'Add messages and comments to transfers',
    category: 'transfer',
    status: 'implemented',
    icon: '💬',
  },

  // Network Features (30+)
  {
    id: 'net-001',
    title: 'mDNS Discovery',
    description: 'Automatic local network device discovery',
    category: 'network',
    status: 'implemented',
    icon: '📡',
    relatedFiles: ['lib/discovery/mdns-bridge.ts'],
  },
  {
    id: 'net-002',
    title: 'NAT Traversal',
    description: 'STUN/TURN servers for NAT traversal',
    category: 'network',
    status: 'implemented',
    icon: '🌐',
  },
  {
    id: 'net-003',
    title: 'NAT Detection',
    description: 'Detect NAT type for optimal connection',
    category: 'network',
    status: 'implemented',
    icon: '🔍',
    relatedFiles: ['lib/network/nat-detection.ts'],
  },
  {
    id: 'net-004',
    title: 'Onion Routing',
    description: 'Multi-hop routing for enhanced privacy',
    category: 'network',
    status: 'implemented',
    icon: '🧅',
    relatedFiles: ['lib/transport/onion-routing.ts'],
  },
  {
    id: 'net-005',
    title: 'Traffic Obfuscation',
    description: 'Disguise traffic patterns to prevent analysis',
    category: 'network',
    status: 'implemented',
    icon: '🎭',
    relatedFiles: ['lib/transport/obfuscation.ts'],
  },
  {
    id: 'net-006',
    title: 'WebRTC Data Channels',
    description: 'Low-latency peer-to-peer data channels',
    category: 'network',
    status: 'implemented',
    icon: '📡',
  },
  {
    id: 'net-007',
    title: 'WebSocket Fallback',
    description: 'WebSocket fallback when P2P fails',
    category: 'network',
    status: 'implemented',
    icon: '🔌',
  },
  {
    id: 'net-008',
    title: 'Connection Quality',
    description: 'Monitor and display connection quality',
    category: 'network',
    status: 'implemented',
    icon: '📶',
  },
  {
    id: 'net-009',
    title: 'Network Diagnostics',
    description: 'Built-in network diagnostic tools',
    category: 'network',
    status: 'implemented',
    icon: '🔧',
  },
  {
    id: 'net-010',
    title: 'IPv6 Support',
    description: 'Full IPv6 compatibility',
    category: 'network',
    status: 'implemented',
    icon: '🌐',
  },
  {
    id: 'net-011',
    title: 'Bandwidth Detection',
    description: 'Auto-detect available bandwidth',
    category: 'network',
    status: 'implemented',
    icon: '📊',
  },
  {
    id: 'net-012',
    title: 'Unified Discovery',
    description: 'Combined local and internet discovery',
    category: 'network',
    status: 'implemented',
    icon: '🔍',
    relatedFiles: ['lib/discovery/unified-discovery.ts'],
  },
  {
    id: 'net-013',
    title: 'Group Discovery',
    description: 'Discover multiple peers in a group',
    category: 'network',
    status: 'implemented',
    icon: '👥',
    relatedFiles: ['lib/discovery/group-discovery.ts'],
  },
  {
    id: 'net-014',
    title: 'Daemon Integration',
    description: 'System daemon for background discovery',
    category: 'network',
    status: 'implemented',
    icon: '⚙️',
    relatedFiles: ['lib/discovery/daemon-integration.ts'],
  },
  {
    id: 'net-015',
    title: 'Relay Server',
    description: 'Fallback relay when direct connection fails',
    category: 'network',
    status: 'implemented',
    icon: '🔄',
  },
  {
    id: 'net-016',
    title: 'Connection Pooling',
    description: 'Reuse connections for efficiency',
    category: 'network',
    status: 'implemented',
    icon: '🏊',
  },
  {
    id: 'net-017',
    title: 'Auto-Reconnect',
    description: 'Automatically reconnect on network changes',
    category: 'network',
    status: 'implemented',
    icon: '🔁',
  },
  {
    id: 'net-018',
    title: 'Network Change Detection',
    description: 'Detect and adapt to network changes',
    category: 'network',
    status: 'implemented',
    icon: '🔄',
  },
  {
    id: 'net-019',
    title: 'Bluetooth Discovery',
    description: 'Discover nearby devices via Bluetooth',
    category: 'network',
    status: 'planned',
    icon: '📶',
  },
  {
    id: 'net-020',
    title: 'Mesh Networking',
    description: 'Multi-peer mesh network support',
    category: 'network',
    status: 'planned',
    icon: '🕸️',
  },
  {
    id: 'net-021',
    title: 'Connection Priority',
    description: 'Prioritize connections based on quality',
    category: 'network',
    status: 'implemented',
    icon: '🎯',
  },
  {
    id: 'net-022',
    title: 'Firewall Detection',
    description: 'Detect and work around firewalls',
    category: 'network',
    status: 'implemented',
    icon: '🛡️',
  },
  {
    id: 'net-023',
    title: 'Port Forwarding',
    description: 'UPnP automatic port forwarding',
    category: 'network',
    status: 'planned',
    icon: '🚪',
  },
  {
    id: 'net-024',
    title: 'Network Metrics',
    description: 'Detailed network performance metrics',
    category: 'network',
    status: 'implemented',
    icon: '📈',
  },
  {
    id: 'net-025',
    title: 'Latency Optimization',
    description: 'Minimize latency with smart routing',
    category: 'network',
    status: 'implemented',
    icon: '⚡',
  },
  {
    id: 'net-026',
    title: 'Packet Loss Recovery',
    description: 'Recover from packet loss gracefully',
    category: 'network',
    status: 'implemented',
    icon: '🔧',
  },
  {
    id: 'net-027',
    title: 'Jitter Buffering',
    description: 'Handle network jitter effectively',
    category: 'network',
    status: 'implemented',
    icon: '📊',
  },
  {
    id: 'net-028',
    title: 'Multi-Path Routing',
    description: 'Use multiple network paths simultaneously',
    category: 'network',
    status: 'planned',
    icon: '🛤️',
  },
  {
    id: 'net-029',
    title: 'Network Profiles',
    description: 'Save and switch between network profiles',
    category: 'network',
    status: 'planned',
    icon: '📋',
  },
  {
    id: 'net-030',
    title: 'Connection Timeout',
    description: 'Configurable connection timeout',
    category: 'network',
    status: 'implemented',
    icon: '⏱️',
  },

  // Privacy Features (25+)
  {
    id: 'priv-001',
    title: 'Metadata Stripping',
    description: 'Remove EXIF and metadata from files',
    category: 'privacy',
    status: 'implemented',
    icon: '🧹',
    relatedFiles: ['lib/privacy/metadata-stripper.ts'],
  },
  {
    id: 'priv-002',
    title: 'Video Metadata Removal',
    description: 'Strip metadata from video files',
    category: 'privacy',
    status: 'implemented',
    icon: '🎥',
    relatedFiles: ['lib/privacy/video-metadata-stripper.ts'],
  },
  {
    id: 'priv-003',
    title: 'Privacy Mode',
    description: 'Enhanced privacy with no logging',
    category: 'privacy',
    status: 'implemented',
    icon: '🕵️',
    relatedFiles: ['lib/privacy/privacy-settings.ts'],
  },
  {
    id: 'priv-004',
    title: 'No Account Required',
    description: 'Use without creating an account',
    category: 'privacy',
    status: 'implemented',
    icon: '🚫',
  },
  {
    id: 'priv-005',
    title: 'No Cloud Storage',
    description: 'Files never stored on servers',
    category: 'privacy',
    status: 'implemented',
    icon: '☁️',
  },
  {
    id: 'priv-006',
    title: 'Anonymous Usage',
    description: 'No tracking or analytics',
    category: 'privacy',
    status: 'implemented',
    icon: '🎭',
  },
  {
    id: 'priv-007',
    title: 'IP Masking',
    description: 'Hide your IP address from peers',
    category: 'privacy',
    status: 'planned',
    icon: '🎭',
  },
  {
    id: 'priv-008',
    title: 'Incognito Mode',
    description: 'Leave no local traces',
    category: 'privacy',
    status: 'planned',
    icon: '🥸',
  },
  {
    id: 'priv-009',
    title: 'Self-Destructing Files',
    description: 'Files auto-delete after viewing',
    category: 'privacy',
    status: 'implemented',
    icon: '💣',
  },
  {
    id: 'priv-010',
    title: 'Privacy Dashboard',
    description: 'View and manage privacy settings',
    category: 'privacy',
    status: 'implemented',
    icon: '🎛️',
  },
  {
    id: 'priv-011',
    title: 'Data Minimization',
    description: 'Collect minimal data necessary',
    category: 'privacy',
    status: 'implemented',
    icon: '📉',
  },
  {
    id: 'priv-012',
    title: 'Cookie-Free',
    description: 'No tracking cookies',
    category: 'privacy',
    status: 'implemented',
    icon: '🍪',
  },
  {
    id: 'priv-013',
    title: 'Fingerprint Protection',
    description: 'Prevent browser fingerprinting',
    category: 'privacy',
    status: 'planned',
    icon: '👆',
  },
  {
    id: 'priv-014',
    title: 'Do Not Track',
    description: 'Honor DNT browser settings',
    category: 'privacy',
    status: 'implemented',
    icon: '🚫',
  },
  {
    id: 'priv-015',
    title: 'GDPR Compliant',
    description: 'Full GDPR compliance',
    category: 'privacy',
    status: 'implemented',
    icon: '🇪🇺',
  },
  {
    id: 'priv-016',
    title: 'Data Export',
    description: 'Export all your data anytime',
    category: 'privacy',
    status: 'planned',
    icon: '📦',
  },
  {
    id: 'priv-017',
    title: 'Right to Deletion',
    description: 'Delete all your data permanently',
    category: 'privacy',
    status: 'implemented',
    icon: '🗑️',
  },
  {
    id: 'priv-018',
    title: 'Privacy Policy',
    description: 'Clear, transparent privacy policy',
    category: 'privacy',
    status: 'implemented',
    icon: '📜',
  },
  {
    id: 'priv-019',
    title: 'Terms of Service',
    description: 'Fair, understandable terms',
    category: 'privacy',
    status: 'implemented',
    icon: '📋',
  },
  {
    id: 'priv-020',
    title: 'Open Source',
    description: 'Fully open source for transparency',
    category: 'privacy',
    status: 'implemented',
    icon: '🔓',
  },
  {
    id: 'priv-021',
    title: 'Audit Trail',
    description: 'Local audit log of your activity',
    category: 'privacy',
    status: 'implemented',
    icon: '📝',
  },
  {
    id: 'priv-022',
    title: 'Consent Management',
    description: 'Granular control over permissions',
    category: 'privacy',
    status: 'implemented',
    icon: '✅',
  },
  {
    id: 'priv-023',
    title: 'Private by Default',
    description: 'Privacy settings enabled by default',
    category: 'privacy',
    status: 'implemented',
    icon: '🔒',
  },
  {
    id: 'priv-024',
    title: 'No Third-Party Scripts',
    description: 'Zero external tracking scripts',
    category: 'privacy',
    status: 'implemented',
    icon: '🚫',
  },
  {
    id: 'priv-025',
    title: 'Local Storage Only',
    description: 'All data stored locally on your device',
    category: 'privacy',
    status: 'implemented',
    icon: '💾',
  },

  // UI Features (30+)
  {
    id: 'ui-001',
    title: 'Dark Mode',
    description: 'Beautiful dark theme for low-light environments',
    category: 'ui',
    status: 'implemented',
    icon: '🌙',
  },
  {
    id: 'ui-002',
    title: 'Light Mode',
    description: 'Clean light theme for daytime use',
    category: 'ui',
    status: 'implemented',
    icon: '☀️',
  },
  {
    id: 'ui-003',
    title: 'Auto Theme',
    description: 'Automatically switch based on system preference',
    category: 'ui',
    status: 'implemented',
    icon: '🎨',
  },
  {
    id: 'ui-004',
    title: 'Responsive Design',
    description: 'Works perfectly on all screen sizes',
    category: 'ui',
    status: 'implemented',
    icon: '📱',
  },
  {
    id: 'ui-005',
    title: 'Accessibility',
    description: 'WCAG 2.1 AA compliant',
    category: 'ui',
    status: 'implemented',
    icon: '♿',
  },
  {
    id: 'ui-006',
    title: 'Keyboard Navigation',
    description: 'Full keyboard support',
    category: 'ui',
    status: 'implemented',
    icon: '⌨️',
  },
  {
    id: 'ui-007',
    title: 'Screen Reader Support',
    description: 'Optimized for screen readers',
    category: 'ui',
    status: 'implemented',
    icon: '🔊',
  },
  {
    id: 'ui-008',
    title: 'Focus Indicators',
    description: 'Clear focus indicators for navigation',
    category: 'ui',
    status: 'implemented',
    icon: '🎯',
  },
  {
    id: 'ui-009',
    title: 'Skip Links',
    description: 'Skip to main content links',
    category: 'ui',
    status: 'implemented',
    icon: '⏭️',
  },
  {
    id: 'ui-010',
    title: 'Toast Notifications',
    description: 'Non-intrusive toast messages',
    category: 'ui',
    status: 'implemented',
    icon: '📬',
  },
  {
    id: 'ui-011',
    title: 'Modal Dialogs',
    description: 'Accessible modal dialogs',
    category: 'ui',
    status: 'implemented',
    icon: '🪟',
  },
  {
    id: 'ui-012',
    title: 'Loading States',
    description: 'Clear loading indicators',
    category: 'ui',
    status: 'implemented',
    icon: '⏳',
  },
  {
    id: 'ui-013',
    title: 'Error States',
    description: 'Helpful error messages',
    category: 'ui',
    status: 'implemented',
    icon: '❌',
  },
  {
    id: 'ui-014',
    title: 'Empty States',
    description: 'Informative empty state designs',
    category: 'ui',
    status: 'implemented',
    icon: '📭',
  },
  {
    id: 'ui-015',
    title: 'Animations',
    description: 'Smooth, performant animations',
    category: 'ui',
    status: 'implemented',
    icon: '✨',
  },
  {
    id: 'ui-016',
    title: 'Reduced Motion',
    description: 'Respect prefers-reduced-motion',
    category: 'ui',
    status: 'implemented',
    icon: '🎬',
  },
  {
    id: 'ui-017',
    title: 'Design System',
    description: 'Comprehensive design system',
    category: 'ui',
    status: 'implemented',
    icon: '🎨',
  },
  {
    id: 'ui-018',
    title: 'Component Library',
    description: 'Reusable UI components',
    category: 'ui',
    status: 'implemented',
    icon: '🧩',
  },
  {
    id: 'ui-019',
    title: 'Typography System',
    description: 'Beautiful, accessible typography',
    category: 'ui',
    status: 'implemented',
    icon: '🔤',
  },
  {
    id: 'ui-020',
    title: 'Color Palette',
    description: 'Carefully crafted color system',
    category: 'ui',
    status: 'implemented',
    icon: '🎨',
  },
  {
    id: 'ui-021',
    title: 'Spacing System',
    description: 'Consistent spacing scales',
    category: 'ui',
    status: 'implemented',
    icon: '📏',
  },
  {
    id: 'ui-022',
    title: 'Icon System',
    description: 'Comprehensive icon library',
    category: 'ui',
    status: 'implemented',
    icon: '🎭',
  },
  {
    id: 'ui-023',
    title: 'Forms',
    description: 'Well-designed form components',
    category: 'ui',
    status: 'implemented',
    icon: '📝',
  },
  {
    id: 'ui-024',
    title: 'Buttons',
    description: 'Various button styles and states',
    category: 'ui',
    status: 'implemented',
    icon: '🔘',
  },
  {
    id: 'ui-025',
    title: 'Cards',
    description: 'Flexible card components',
    category: 'ui',
    status: 'implemented',
    icon: '🃏',
  },
  {
    id: 'ui-026',
    title: 'Badges',
    description: 'Status and notification badges',
    category: 'ui',
    status: 'implemented',
    icon: '🏷️',
  },
  {
    id: 'ui-027',
    title: 'Progress Bars',
    description: 'Visual progress indicators',
    category: 'ui',
    status: 'implemented',
    icon: '📊',
  },
  {
    id: 'ui-028',
    title: 'Tooltips',
    description: 'Contextual help tooltips',
    category: 'ui',
    status: 'implemented',
    icon: '💡',
  },
  {
    id: 'ui-029',
    title: 'Dropdowns',
    description: 'Accessible dropdown menus',
    category: 'ui',
    status: 'implemented',
    icon: '⬇️',
  },
  {
    id: 'ui-030',
    title: 'Tables',
    description: 'Responsive data tables',
    category: 'ui',
    status: 'implemented',
    icon: '📊',
  },

  // Chat Features (15+)
  {
    id: 'chat-001',
    title: 'P2P Chat',
    description: 'End-to-end encrypted peer chat',
    category: 'chat',
    status: 'implemented',
    icon: '💬',
  },
  {
    id: 'chat-002',
    title: 'Group Chat',
    description: 'Multi-user encrypted group chat',
    category: 'chat',
    status: 'implemented',
    icon: '👥',
  },
  {
    id: 'chat-003',
    title: 'File Sharing in Chat',
    description: 'Share files directly in chat',
    category: 'chat',
    status: 'implemented',
    icon: '📎',
  },
  {
    id: 'chat-004',
    title: 'Chat History',
    description: 'Local chat history storage',
    category: 'chat',
    status: 'implemented',
    icon: '📜',
    relatedFiles: ['lib/chat/chat-storage.ts'],
  },
  {
    id: 'chat-005',
    title: 'Chat Manager',
    description: 'Manage multiple chat sessions',
    category: 'chat',
    status: 'implemented',
    icon: '🎛️',
    relatedFiles: ['lib/chat/chat-manager.ts'],
  },
  {
    id: 'chat-006',
    title: 'Typing Indicators',
    description: 'See when others are typing',
    category: 'chat',
    status: 'implemented',
    icon: '⌨️',
  },
  {
    id: 'chat-007',
    title: 'Read Receipts',
    description: 'Message read confirmation',
    category: 'chat',
    status: 'implemented',
    icon: '✅',
  },
  {
    id: 'chat-008',
    title: 'Message Reactions',
    description: 'React to messages with emoji',
    category: 'chat',
    status: 'planned',
    icon: '😄',
  },
  {
    id: 'chat-009',
    title: 'Message Search',
    description: 'Search through chat history',
    category: 'chat',
    status: 'implemented',
    icon: '🔍',
  },
  {
    id: 'chat-010',
    title: 'Message Formatting',
    description: 'Markdown formatting support',
    category: 'chat',
    status: 'planned',
    icon: '📝',
  },
  {
    id: 'chat-011',
    title: 'Code Blocks',
    description: 'Share code with syntax highlighting',
    category: 'chat',
    status: 'planned',
    icon: '💻',
  },
  {
    id: 'chat-012',
    title: 'Voice Messages',
    description: 'Send voice messages',
    category: 'chat',
    status: 'planned',
    icon: '🎤',
  },
  {
    id: 'chat-013',
    title: 'Video Chat',
    description: 'Peer-to-peer video calls',
    category: 'chat',
    status: 'planned',
    icon: '📹',
  },
  {
    id: 'chat-014',
    title: 'Screen Sharing',
    description: 'Share your screen with peers',
    category: 'chat',
    status: 'implemented',
    icon: '🖥️',
  },
  {
    id: 'chat-015',
    title: 'Chat Notifications',
    description: 'Desktop notifications for messages',
    category: 'chat',
    status: 'implemented',
    icon: '🔔',
  },

  // Friends/Contacts (10+)
  {
    id: 'friend-001',
    title: 'Friends List',
    description: 'Manage your trusted contacts',
    category: 'friends',
    status: 'planned',
    icon: '👥',
  },
  {
    id: 'friend-002',
    title: 'Friend Requests',
    description: 'Send and receive friend requests',
    category: 'friends',
    status: 'planned',
    icon: '🤝',
  },
  {
    id: 'friend-003',
    title: 'Favorites',
    description: 'Mark favorite contacts',
    category: 'friends',
    status: 'planned',
    icon: '⭐',
  },
  {
    id: 'friend-004',
    title: 'Contact Groups',
    description: 'Organize contacts into groups',
    category: 'friends',
    status: 'planned',
    icon: '📁',
  },
  {
    id: 'friend-005',
    title: 'Contact Search',
    description: 'Search through contacts',
    category: 'friends',
    status: 'planned',
    icon: '🔍',
  },
  {
    id: 'friend-006',
    title: 'Online Status',
    description: 'See when friends are online',
    category: 'friends',
    status: 'planned',
    icon: '🟢',
  },
  {
    id: 'friend-007',
    title: 'Profile Pictures',
    description: 'Custom profile pictures',
    category: 'friends',
    status: 'planned',
    icon: '🖼️',
  },
  {
    id: 'friend-008',
    title: 'Nicknames',
    description: 'Set custom nicknames for contacts',
    category: 'friends',
    status: 'planned',
    icon: '📝',
  },
  {
    id: 'friend-009',
    title: 'Block List',
    description: 'Block unwanted contacts',
    category: 'friends',
    status: 'planned',
    icon: '🚫',
  },
  {
    id: 'friend-010',
    title: 'Contact Sync',
    description: 'Sync contacts across devices',
    category: 'friends',
    status: 'planned',
    icon: '🔄',
  },

  // Settings & Crypto (15+)
  {
    id: 'set-001',
    title: 'Settings Panel',
    description: 'Comprehensive settings interface',
    category: 'settings',
    status: 'implemented',
    icon: '⚙️',
  },
  {
    id: 'set-002',
    title: 'Preferences',
    description: 'Customize app behavior',
    category: 'settings',
    status: 'implemented',
    icon: '🎛️',
  },
  {
    id: 'set-003',
    title: 'Notifications Settings',
    description: 'Control notification preferences',
    category: 'settings',
    status: 'implemented',
    icon: '🔔',
  },
  {
    id: 'set-004',
    title: 'Privacy Settings',
    description: 'Granular privacy controls',
    category: 'settings',
    status: 'implemented',
    icon: '🔒',
  },
  {
    id: 'set-005',
    title: 'Network Settings',
    description: 'Configure network preferences',
    category: 'settings',
    status: 'implemented',
    icon: '🌐',
  },
  {
    id: 'set-006',
    title: 'Storage Settings',
    description: 'Manage local storage',
    category: 'settings',
    status: 'implemented',
    icon: '💾',
  },
  {
    id: 'set-007',
    title: 'Language Settings',
    description: 'Multi-language support',
    category: 'settings',
    status: 'planned',
    icon: '🌍',
  },
  {
    id: 'set-008',
    title: 'Keyboard Shortcuts',
    description: 'Customizable keyboard shortcuts',
    category: 'settings',
    status: 'implemented',
    icon: '⌨️',
  },
  {
    id: 'set-009',
    title: 'Advanced Settings',
    description: 'Power user settings',
    category: 'settings',
    status: 'implemented',
    icon: '🔧',
  },
  {
    id: 'set-010',
    title: 'Settings Export',
    description: 'Export settings configuration',
    category: 'settings',
    status: 'planned',
    icon: '📤',
  },
  {
    id: 'crypto-001',
    title: 'Crypto Worker',
    description: 'Background worker for crypto operations',
    category: 'crypto',
    status: 'implemented',
    icon: '⚙️',
    relatedFiles: ['lib/workers/crypto.worker.ts'],
  },
  {
    id: 'crypto-002',
    title: 'Lazy PQC Loading',
    description: 'Load post-quantum crypto on demand',
    category: 'crypto',
    status: 'implemented',
    icon: '⚡',
    relatedFiles: ['lib/crypto/pqc-lazy.ts'],
  },
  {
    id: 'crypto-003',
    title: 'File Encryption PQC',
    description: 'Post-quantum file encryption',
    category: 'crypto',
    status: 'implemented',
    icon: '🔒',
    relatedFiles: ['lib/crypto/file-encryption-pqc.ts'],
  },
  {
    id: 'crypto-004',
    title: 'Password File Encryption',
    description: 'Password-based file encryption',
    category: 'crypto',
    status: 'implemented',
    icon: '🔐',
    relatedFiles: ['lib/crypto/password-file-encryption.ts'],
  },
  {
    id: 'crypto-005',
    title: 'Input Validation',
    description: 'Cryptographic input validation',
    category: 'crypto',
    status: 'implemented',
    icon: '✅',
    relatedFiles: ['lib/crypto/input-validation.ts'],
  },

  // Performance Features (20+)
  {
    id: 'perf-001',
    title: 'Code Splitting',
    description: 'Automatic code splitting for faster loads',
    category: 'performance',
    status: 'implemented',
    icon: '✂️',
  },
  {
    id: 'perf-002',
    title: 'Lazy Loading',
    description: 'Load components on demand',
    category: 'performance',
    status: 'implemented',
    icon: '⏳',
    relatedFiles: ['lib/performance/lazy-load.ts'],
  },
  {
    id: 'perf-003',
    title: 'Image Optimization',
    description: 'Automatic image optimization',
    category: 'performance',
    status: 'implemented',
    icon: '🖼️',
    relatedFiles: ['lib/performance/image-optimization.ts'],
  },
  {
    id: 'perf-004',
    title: 'Font Optimization',
    description: 'Optimized font loading',
    category: 'performance',
    status: 'implemented',
    icon: '🔤',
    relatedFiles: ['lib/performance/font-optimization.ts'],
  },
  {
    id: 'perf-005',
    title: 'Resource Prefetching',
    description: 'Prefetch critical resources',
    category: 'performance',
    status: 'implemented',
    icon: '🚀',
    relatedFiles: ['lib/performance/prefetch.ts'],
  },
  {
    id: 'perf-006',
    title: 'Route Prefetching',
    description: 'Prefetch next likely routes',
    category: 'performance',
    status: 'implemented',
    icon: '🗺️',
    relatedFiles: ['lib/prefetch/route-prefetcher.ts'],
  },
  {
    id: 'perf-007',
    title: 'Performance Monitoring',
    description: 'Real-time performance metrics',
    category: 'performance',
    status: 'implemented',
    icon: '📊',
    relatedFiles: ['lib/performance/monitoring.ts'],
  },
  {
    id: 'perf-008',
    title: 'Error Boundary',
    description: 'Graceful error handling',
    category: 'performance',
    status: 'implemented',
    icon: '🛡️',
    relatedFiles: ['lib/performance/error-boundary.tsx'],
  },
  {
    id: 'perf-009',
    title: 'Cache Strategy',
    description: 'Intelligent caching strategies',
    category: 'performance',
    status: 'implemented',
    icon: '💾',
    relatedFiles: ['lib/cache/cache-strategy.ts'],
  },
  {
    id: 'perf-010',
    title: 'Cache Busting',
    description: 'Automatic cache invalidation',
    category: 'performance',
    status: 'implemented',
    icon: '🔄',
    relatedFiles: ['lib/utils/cache-buster.ts'],
  },
  {
    id: 'perf-011',
    title: 'Service Worker',
    description: 'Offline support with service workers',
    category: 'performance',
    status: 'planned',
    icon: '⚙️',
  },
  {
    id: 'perf-012',
    title: 'Progressive Web App',
    description: 'PWA features for mobile',
    category: 'performance',
    status: 'planned',
    icon: '📱',
  },
  {
    id: 'perf-013',
    title: 'Virtual Scrolling',
    description: 'Efficient rendering of large lists',
    category: 'performance',
    status: 'planned',
    icon: '📜',
  },
  {
    id: 'perf-014',
    title: 'Debouncing',
    description: 'Debounce expensive operations',
    category: 'performance',
    status: 'implemented',
    icon: '⏱️',
  },
  {
    id: 'perf-015',
    title: 'Throttling',
    description: 'Throttle frequent events',
    category: 'performance',
    status: 'implemented',
    icon: '🎚️',
  },
  {
    id: 'perf-016',
    title: 'Memoization',
    description: 'Cache expensive computations',
    category: 'performance',
    status: 'implemented',
    icon: '🧠',
  },
  {
    id: 'perf-017',
    title: 'Bundle Analysis',
    description: 'Analyze and optimize bundle size',
    category: 'performance',
    status: 'implemented',
    icon: '📦',
  },
  {
    id: 'perf-018',
    title: 'Tree Shaking',
    description: 'Remove unused code',
    category: 'performance',
    status: 'implemented',
    icon: '🌳',
  },
  {
    id: 'perf-019',
    title: 'Minification',
    description: 'Minify JavaScript and CSS',
    category: 'performance',
    status: 'implemented',
    icon: '📉',
  },
  {
    id: 'perf-020',
    title: 'Compression',
    description: 'Gzip and Brotli compression',
    category: 'performance',
    status: 'implemented',
    icon: '🗜️',
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All', count: FEATURES.length },
  {
    id: 'security',
    label: 'Security',
    count: FEATURES.filter((f) => f.category === 'security').length,
  },
  {
    id: 'transfer',
    label: 'Transfer',
    count: FEATURES.filter((f) => f.category === 'transfer').length,
  },
  {
    id: 'network',
    label: 'Network',
    count: FEATURES.filter((f) => f.category === 'network').length,
  },
  {
    id: 'privacy',
    label: 'Privacy',
    count: FEATURES.filter((f) => f.category === 'privacy').length,
  },
  { id: 'ui', label: 'UI', count: FEATURES.filter((f) => f.category === 'ui').length },
  {
    id: 'chat',
    label: 'Chat',
    count: FEATURES.filter((f) => f.category === 'chat').length,
  },
  {
    id: 'friends',
    label: 'Friends',
    count: FEATURES.filter((f) => f.category === 'friends').length,
  },
  {
    id: 'settings',
    label: 'Settings',
    count: FEATURES.filter((f) => f.category === 'settings').length,
  },
  {
    id: 'crypto',
    label: 'Crypto',
    count: FEATURES.filter((f) => f.category === 'crypto').length,
  },
  {
    id: 'performance',
    label: 'Performance',
    count: FEATURES.filter((f) => f.category === 'performance').length,
  },
] as const;

export const STATUSES = [
  { id: 'all', label: 'All', count: FEATURES.length },
  {
    id: 'implemented',
    label: 'Implemented',
    count: FEATURES.filter((f) => f.status === 'implemented').length,
  },
  {
    id: 'in-progress',
    label: 'In Progress',
    count: FEATURES.filter((f) => f.status === 'in-progress').length,
  },
  {
    id: 'planned',
    label: 'Planned',
    count: FEATURES.filter((f) => f.status === 'planned').length,
  },
] as const;
